GET http://localhost:3001

### Fetch all products request
GET http://localhost:3001/products

### Fetch one product request
GET http://localhost:3001/products/1

### Create new products request
POST http://localhost:3001/products
Content-Type: application/json

{
  "name": "",
  "label": "",
  "price": ,
  "imageURL": "",
  "description": "",
  "categories": [""],
  "productType": "",
  "brand": ""
}


### Update products request
PUT http://localhost:3001/products/1
Content-Type: application/json

{

}

### Delete product request
DELETE http://localhost:3001/products/1
Content-Type: application/json

{

}